esphome:
  name: testc6
  friendly_name: testC6

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CB/m9PsxVn8m+uoL5GDmErhq9dGAnh5SCuyLaPXGPkE="

ota:
  - platform: esphome
    password: "6157643ffe6d53e9532a9b1a841c3486"

wifi:
  ssid: !secret wifi_ssid_test
  password: !secret wifi_password_test

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testc6 Fallback Hotspot"
    password: "QWPYIM1T9SmZ"

captive_portal:

output:
  - platform: gpio
    pin: GPIO15
    id: light_output
    inverted: True

# external light
light:
  - platform: binary
    name: "Onboard Light"
    output: light_output
    id: onBoardLight
